### ISSUE TITLE
No Image

### ISSUE THREAD

**Issue by hollanda1357** [kurtern84/MMM-profile#1]
I have followed all steps like you laid out and no image shows up. I can provide logs of whatever helps but there are no errors or anything it just doesn't show up. Only thing I can think of is do you have to have Magic Mirror v2.1.0 exactly, or can it be upgraded further than that? 

Thank you for your help.

**Comment by kurtern84** [comment]
@hollanda1357 That´s odd. It´s my first modul so maybe its something i dont know. I am new to this :)
But i am running on the latest MM with no problem with the modul.

Can you post your config file?

**Comment by hollanda1357** [comment]
I figured it out. Had to change some stuff in my config file for my specific raspberry pi but I got it all working now. :) 
Thanks for your help.

**Comment by kurtern84** [comment]
Great! :)

**Comment by hollanda1357** [comment]
Just curious is there any way to get rid of the compliments portion of the module or is that not possible? It doesn’t fit well with the other modules I have installed and would be awesome if I could take that part off and keep the picture and welcome text. 
Thanks in advance.
