### ISSUE TITLE
How to get rid of compliments?

### ISSUE THREAD

**Issue by hollanda1357** [kurtern84/MMM-profile#2]
Hello, I have installed this module and have everything working perfectly how it’s supposed to but was wondering if it was possible to get rid of the compliments feature? With the way mine is set up I only want the image and welcome message and need a way to get rid of the compliments as they do not fit in with the rest of the modules how I would like them too. Is this at all possible?
Thanks in advance.

**Comment by santiagos5** [comment]
i'm interesting too.. i simply put "spaces" in each condition compliments, so nothing appear, but every first time i load MM appear "undefined" but after a refresh disappear.. 
It's only a workaround, i would prefear an option to show or not..

**Comment by hollanda1357** [comment]
thank you. I was actually recently working on it and stumbled across that same solution myself... I also have the problem with the undefined text before it disappears and am trying to figure out a workaround to that. let me know if you figure it out! 
thanks again
